### ISSUE TITLE
I get an error when i run your script..

### ISSUE THREAD

**Issue by id535** [adamb70/CSGO-skin-ID-dumper#4]
Traceback (most recent call last):
  File "c:\users\id\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 80, in <module>
    outfile.write("%s: %s\n" % (n, namedata[tag.lower()].encode('utf-8')))
ValueError: I/O operation on closed file.
Press any key to continue . . .

What did i do wrong and how do i fix this. 
PS: I copy pasted the source

**Comment by adamb70** [comment]
Check the indentation of the last line, you might have removed spaces so the call to write() is outside the with block

**Comment by croatek** [comment]
line 75, in <module> with open('item_index.txt', 'w') as outfile:
PermissionError: [Errno 13] Permission denied: 'item_index.txt'

how fix this?

**Comment by adamb70** [comment]
@croatek Do you have write permissions in the folder you're running the script, and check that the `item_index.txt` file isn't set to read-only

**Comment by croatek** [comment]
@adamb70, i have write permissions, but now i start script and nothing happens. help me please

**Comment by adamb70** [comment]
Which version of Python are you using? I've just updated the script to work better on both 2.7 and 3, so give the new version a try.

**Comment by id535** [comment]
The updated script works for me now. Thanks
