### ISSUE TITLE
Listing what skin its used on?

### ISSUE THREAD

**Issue by DigidyDog** [adamb70/CSGO-skin-ID-dumper#6]
Is there a way to also add what gun the skin is defaultly for?

say M4A4 ### skinname

If this could be done that would be AWESOME!

**Comment by adamb70** [comment]
Probably out of the scope of this script anyway, but I don't believe skins are tied to any weapon by default. See the Safari Mesh being available on the AWP, AK47, G3SG1, and knives for example.
